apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "500m"
      ports:
        - containerPort: 80