FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o server server.go
FROM debian:bullseye-slim
WORKDIR /root/
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/server .
RUN chmod +x ./server
EXPOSE 8080
CMD ["./server"]
